//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMVCSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int BillDetailID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<double> ProductTotal { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
